SET SEARCH_PATH = kvartirum;

CREATE TABLE IF NOT EXISTS Views(
    id BIGINT GENERATED ALWAYS AS IDENTITY
    PRIMARY KEY,
    offer_id BIGINT NOT NULL
    REFERENCES Offer (id)
    ON DELETE cascade
    ON UPDATE cascade,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
); 