SET SEARCH_PATH = kvartirum;

ALTER TABLE Offer 
ALTER COLUMN price DROP DEFAULT,
ALTER COLUMN floor DROP DEFAULT,
ALTER COLUMN total_floors DROP DEFAULT,
ALTER COLUMN rooms DROP DEFAULT,
ALTER COLUMN flat DROP DEFAULT,
ALTER COLUMN area DROP DEFAULT,
ALTER COLUMN ceiling_height DROP DEFAULT,
ALTER COLUMN address DROP DEFAULT;

DROP TRIGGER IF EXISTS trg_offer_defaults ON Offer;
DROP FUNCTION IF EXISTS set_offer_defaults();