SET SEARCH_PATH = kvartirum;

DROP TABLE IF EXISTS HousingComplexClass;
DROP TABLE IF EXISTS offerrenovation;
DROP TABLE IF EXISTS OfferStatus;
DROP TABLE IF EXISTS propertytype;
DROP TABLE IF EXISTS purchasetype;
DROP TABLE IF EXISTS renttype;
DROP TABLE IF EXISTS metrostation;
DROP TABLE IF EXISTS metroline;
DROP TABLE IF EXISTS Offertype;