{
 "title": "Kvartirum Dashboard",
 "time": { "from": "2025-05-04T18:09:22.719Z", "to": "2025-05-04T20:42:41.641Z" },
 "panels": [
  {
   "title": "Auth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests (auth)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by(method, path, status) (\n  rate(http_request_total{service=\"auth\", status=~\"2..\"}[1m])\n)",
       "legendFormat": "{{path}}_{{method}}.{{status}}"
      }
     ]
    },
    {
     "title": "Total ClientErrors (auth)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by(method, path, status) (\n  rate(http_errors_total{service=\"auth\", status=~\"4..\"}[1m])\n)",
       "legendFormat": "{{path}}_{{method}}.{{status}}"
      }
     ]
    },
    {
     "title": "Latency (ms) (auth)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95,\n  sum by(path, le) (\n    rate(http_request_duration_seconds_bucket{service=\"auth\"}[1m])\n  )\n)",
       "legendFormat": "{{path}} - p95"
      }
     ]
    },
    {
     "title": "Total ServerErrors (auth)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
     "targets": [
      {
       "expr": "sum by(method, path, status) (\n  rate(http_errors_total{service=\"auth\", status=~\"5..\"}[1m])\n)",
       "legendFormat": "{{path}}_{{method}}.{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Offer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests (offer)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by(method, path, status) (\n  rate(http_request_total{service=\"offer\", status=~\"2..\"}[1m])\n)",
       "legendFormat": "{{path}}_{{method}}.{{status}}"
      }
     ]
    },
    {
     "title": "Total ClientErrors (offer)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum by(method, path, status) (\n  rate(http_errors_total{service=\"offer\", status=~\"4..\"}[1m])\n)",
       "legendFormat": "{{path}}_{{method}}.{{status}}"
      }
     ]
    },
    {
     "title": "Latency (ms) (offer)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95,\n  sum by(path, le) (\n    rate(http_request_duration_seconds_bucket{service=\"offer\"}[1m])\n  )\n)",
       "legendFormat": "{{path}} - p95"
      }
     ]
    },
    {
     "title": "Total ServerErrors (offer)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum by(method, path, status) (\n  rate(http_errors_total{service=\"offer\", status=~\"5..\"}[1m])\n)",
       "legendFormat": "{{path}}_{{method}}.{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zhk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests (zhk)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by(method, path, status) (\n  rate(http_request_total{service=\"zhk\",status=~\"2..\"}[1m])\n)",
       "legendFormat": "{{path}}_{{method}}.{{status}}"
      }
     ]
    },
    {
     "title": "Total ClientErrors (zhk)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum by(method, path, status) (\n  rate(http_errors_total{service=\"zhk\", status=~\"4..\"}[1m])\n)",
       "legendFormat": "{{path}}_{{method}}.{{status}}"
      }
     ]
    },
    {
     "title": "Latency (ms) (zhk)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95,\n  sum by(path, le) (\n    rate(http_request_duration_seconds_bucket{service=\"zhk\"}[1m])\n  )\n)",
       "legendFormat": "{{path}} - p95"
      }
     ]
    },
    {
     "title": "Total ServerErrors (zhk)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum by(method, path, status) (\n  rate(http_errors_total{service=\"zhk\", status=~\"5..\"}[1m])\n)",
       "legendFormat": "{{path}}_{{method}}.{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ai",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests (ai)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
     "targets": [
      {
       "expr": "sum by(method, path, status) (\n  rate(http_request_total{service=\"ai\", status=~\"2..\"}[1m])\n)",
       "legendFormat": "{{path}}_{{method}}.{{status}}"
      }
     ]
    },
    {
     "title": "Total ClientErrors (ai)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
     "targets": [
      {
       "expr": "sum by(method, path, status) (\n  rate(http_errors_total{service=\"ai\", status=~\"4..\"}[1m])\n)",
       "legendFormat": "{{path}}_{{method}}.{{status}}"
      }
     ]
    },
    {
     "title": "Latency (ms) (ai)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95,\n  sum by(path, le) (\n    rate(http_request_duration_seconds_bucket{service=\"ai\"}[1m])\n  )\n)",
       "legendFormat": "{{path}} - p95"
      }
     ]
    },
    {
     "title": "Total ServerErrors (auth)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
     "targets": [
      {
       "expr": "sum by(method, path, status) (\n  rate(http_errors_total{service=\"ai\", status=~\"5..\"}[1m])\n)",
       "legendFormat": "{{path}}_{{method}}.{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1092 },
     "targets": [
      {
       "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1099 },
     "targets": [
      {
       "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1099 },
     "targets": [
      {
       "expr": "100 * (node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"}) / node_filesystem_size_bytes{mountpoint=\"/\"}\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}