services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data

  minio-client:
    image: minio/mc:latest
    container_name: minio-client
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD};

      mc mb -p local/avatars;
      mc anonymous set download local/avatars;

      mc mb -p local/offers;
      mc anonymous set download local/offers;
      "
    depends_on:
      - minio