// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/offer/offer.proto

package offerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Offer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SellerId       int32                  `protobuf:"varint,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	OfferTypeId    int32                  `protobuf:"varint,3,opt,name=offer_type_id,json=offerTypeId,proto3" json:"offer_type_id,omitempty"`
	MetroStationId *int32                 `protobuf:"varint,4,opt,name=metro_station_id,json=metroStationId,proto3,oneof" json:"metro_station_id,omitempty"`
	RentTypeId     *int32                 `protobuf:"varint,5,opt,name=rent_type_id,json=rentTypeId,proto3,oneof" json:"rent_type_id,omitempty"`
	PurchaseTypeId *int32                 `protobuf:"varint,6,opt,name=purchase_type_id,json=purchaseTypeId,proto3,oneof" json:"purchase_type_id,omitempty"`
	PropertyTypeId int32                  `protobuf:"varint,7,opt,name=property_type_id,json=propertyTypeId,proto3" json:"property_type_id,omitempty"`
	StatusId       int32                  `protobuf:"varint,8,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	RenovationId   int32                  `protobuf:"varint,9,opt,name=renovation_id,json=renovationId,proto3" json:"renovation_id,omitempty"`
	ComplexId      *int32                 `protobuf:"varint,10,opt,name=complex_id,json=complexId,proto3,oneof" json:"complex_id,omitempty"`
	Price          int32                  `protobuf:"varint,11,opt,name=price,proto3" json:"price,omitempty"`
	Description    *string                `protobuf:"bytes,12,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Floor          int32                  `protobuf:"varint,13,opt,name=floor,proto3" json:"floor,omitempty"`
	TotalFloors    int32                  `protobuf:"varint,14,opt,name=total_floors,json=totalFloors,proto3" json:"total_floors,omitempty"`
	Rooms          int32                  `protobuf:"varint,15,opt,name=rooms,proto3" json:"rooms,omitempty"`
	Address        *string                `protobuf:"bytes,16,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Flat           int32                  `protobuf:"varint,17,opt,name=flat,proto3" json:"flat,omitempty"`
	Area           int32                  `protobuf:"varint,18,opt,name=area,proto3" json:"area,omitempty"`
	CeilingHeight  int32                  `protobuf:"varint,19,opt,name=ceiling_height,json=ceilingHeight,proto3" json:"ceiling_height,omitempty"`
	Longitude      string                 `protobuf:"bytes,20,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude       string                 `protobuf:"bytes,21,opt,name=latitude,proto3" json:"latitude,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PromotesUntil  *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=promotes_until,json=promotesUntil,proto3" json:"promotes_until,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_proto_offer_offer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_offer_offer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_proto_offer_offer_proto_rawDescGZIP(), []int{0}
}

func (x *Offer) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Offer) GetSellerId() int32 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *Offer) GetOfferTypeId() int32 {
	if x != nil {
		return x.OfferTypeId
	}
	return 0
}

func (x *Offer) GetMetroStationId() int32 {
	if x != nil && x.MetroStationId != nil {
		return *x.MetroStationId
	}
	return 0
}

func (x *Offer) GetRentTypeId() int32 {
	if x != nil && x.RentTypeId != nil {
		return *x.RentTypeId
	}
	return 0
}

func (x *Offer) GetPurchaseTypeId() int32 {
	if x != nil && x.PurchaseTypeId != nil {
		return *x.PurchaseTypeId
	}
	return 0
}

func (x *Offer) GetPropertyTypeId() int32 {
	if x != nil {
		return x.PropertyTypeId
	}
	return 0
}

func (x *Offer) GetStatusId() int32 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

func (x *Offer) GetRenovationId() int32 {
	if x != nil {
		return x.RenovationId
	}
	return 0
}

func (x *Offer) GetComplexId() int32 {
	if x != nil && x.ComplexId != nil {
		return *x.ComplexId
	}
	return 0
}

func (x *Offer) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Offer) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Offer) GetFloor() int32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *Offer) GetTotalFloors() int32 {
	if x != nil {
		return x.TotalFloors
	}
	return 0
}

func (x *Offer) GetRooms() int32 {
	if x != nil {
		return x.Rooms
	}
	return 0
}

func (x *Offer) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *Offer) GetFlat() int32 {
	if x != nil {
		return x.Flat
	}
	return 0
}

func (x *Offer) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *Offer) GetCeilingHeight() int32 {
	if x != nil {
		return x.CeilingHeight
	}
	return 0
}

func (x *Offer) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *Offer) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *Offer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Offer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Offer) GetPromotesUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.PromotesUntil
	}
	return nil
}

type GetOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfferRequest) Reset() {
	*x = GetOfferRequest{}
	mi := &file_proto_offer_offer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfferRequest) ProtoMessage() {}

func (x *GetOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_offer_offer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfferRequest.ProtoReflect.Descriptor instead.
func (*GetOfferRequest) Descriptor() ([]byte, []int) {
	return file_proto_offer_offer_proto_rawDescGZIP(), []int{1}
}

func (x *GetOfferRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         *Offer                 `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfferResponse) Reset() {
	*x = GetOfferResponse{}
	mi := &file_proto_offer_offer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfferResponse) ProtoMessage() {}

func (x *GetOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_offer_offer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfferResponse.ProtoReflect.Descriptor instead.
func (*GetOfferResponse) Descriptor() ([]byte, []int) {
	return file_proto_offer_offer_proto_rawDescGZIP(), []int{2}
}

func (x *GetOfferResponse) GetOffer() *Offer {
	if x != nil {
		return x.Offer
	}
	return nil
}

type GetOffersByZhkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZhkId         int32                  `protobuf:"varint,1,opt,name=zhk_id,json=zhkId,proto3" json:"zhk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffersByZhkRequest) Reset() {
	*x = GetOffersByZhkRequest{}
	mi := &file_proto_offer_offer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffersByZhkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffersByZhkRequest) ProtoMessage() {}

func (x *GetOffersByZhkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_offer_offer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffersByZhkRequest.ProtoReflect.Descriptor instead.
func (*GetOffersByZhkRequest) Descriptor() ([]byte, []int) {
	return file_proto_offer_offer_proto_rawDescGZIP(), []int{3}
}

func (x *GetOffersByZhkRequest) GetZhkId() int32 {
	if x != nil {
		return x.ZhkId
	}
	return 0
}

type GetOffersByZhkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*Offer               `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffersByZhkResponse) Reset() {
	*x = GetOffersByZhkResponse{}
	mi := &file_proto_offer_offer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffersByZhkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffersByZhkResponse) ProtoMessage() {}

func (x *GetOffersByZhkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_offer_offer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffersByZhkResponse.ProtoReflect.Descriptor instead.
func (*GetOffersByZhkResponse) Descriptor() ([]byte, []int) {
	return file_proto_offer_offer_proto_rawDescGZIP(), []int{4}
}

func (x *GetOffersByZhkResponse) GetOffers() []*Offer {
	if x != nil {
		return x.Offers
	}
	return nil
}

var File_proto_offer_offer_proto protoreflect.FileDescriptor

const file_proto_offer_offer_proto_rawDesc = "" +
	"\n" +
	"\x17proto/offer/offer.proto\x12\fofferService\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\a\n" +
	"\x05Offer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tseller_id\x18\x02 \x01(\x05R\bsellerId\x12\"\n" +
	"\roffer_type_id\x18\x03 \x01(\x05R\vofferTypeId\x12-\n" +
	"\x10metro_station_id\x18\x04 \x01(\x05H\x00R\x0emetroStationId\x88\x01\x01\x12%\n" +
	"\frent_type_id\x18\x05 \x01(\x05H\x01R\n" +
	"rentTypeId\x88\x01\x01\x12-\n" +
	"\x10purchase_type_id\x18\x06 \x01(\x05H\x02R\x0epurchaseTypeId\x88\x01\x01\x12(\n" +
	"\x10property_type_id\x18\a \x01(\x05R\x0epropertyTypeId\x12\x1b\n" +
	"\tstatus_id\x18\b \x01(\x05R\bstatusId\x12#\n" +
	"\rrenovation_id\x18\t \x01(\x05R\frenovationId\x12\"\n" +
	"\n" +
	"complex_id\x18\n" +
	" \x01(\x05H\x03R\tcomplexId\x88\x01\x01\x12\x14\n" +
	"\x05price\x18\v \x01(\x05R\x05price\x12%\n" +
	"\vdescription\x18\f \x01(\tH\x04R\vdescription\x88\x01\x01\x12\x14\n" +
	"\x05floor\x18\r \x01(\x05R\x05floor\x12!\n" +
	"\ftotal_floors\x18\x0e \x01(\x05R\vtotalFloors\x12\x14\n" +
	"\x05rooms\x18\x0f \x01(\x05R\x05rooms\x12\x1d\n" +
	"\aaddress\x18\x10 \x01(\tH\x05R\aaddress\x88\x01\x01\x12\x12\n" +
	"\x04flat\x18\x11 \x01(\x05R\x04flat\x12\x12\n" +
	"\x04area\x18\x12 \x01(\x05R\x04area\x12%\n" +
	"\x0eceiling_height\x18\x13 \x01(\x05R\rceilingHeight\x12\x1c\n" +
	"\tlongitude\x18\x14 \x01(\tR\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x15 \x01(\tR\blatitude\x129\n" +
	"\n" +
	"created_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12A\n" +
	"\x0epromotes_until\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampR\rpromotesUntilB\x13\n" +
	"\x11_metro_station_idB\x0f\n" +
	"\r_rent_type_idB\x13\n" +
	"\x11_purchase_type_idB\r\n" +
	"\v_complex_idB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_address\"!\n" +
	"\x0fGetOfferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"=\n" +
	"\x10GetOfferResponse\x12)\n" +
	"\x05offer\x18\x01 \x01(\v2\x13.offerService.OfferR\x05offer\".\n" +
	"\x15GetOffersByZhkRequest\x12\x15\n" +
	"\x06zhk_id\x18\x01 \x01(\x05R\x05zhkId\"E\n" +
	"\x16GetOffersByZhkResponse\x12+\n" +
	"\x06offers\x18\x01 \x03(\v2\x13.offerService.OfferR\x06offers2\xbc\x01\n" +
	"\fOfferService\x12M\n" +
	"\fGetOfferById\x12\x1d.offerService.GetOfferRequest\x1a\x1e.offerService.GetOfferResponse\x12]\n" +
	"\x10GetOffersByZhkId\x12#.offerService.GetOffersByZhkRequest\x1a$.offerService.GetOffersByZhkResponseB\fZ\n" +
	"./;offerpbb\x06proto3"

var (
	file_proto_offer_offer_proto_rawDescOnce sync.Once
	file_proto_offer_offer_proto_rawDescData []byte
)

func file_proto_offer_offer_proto_rawDescGZIP() []byte {
	file_proto_offer_offer_proto_rawDescOnce.Do(func() {
		file_proto_offer_offer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_offer_offer_proto_rawDesc), len(file_proto_offer_offer_proto_rawDesc)))
	})
	return file_proto_offer_offer_proto_rawDescData
}

var file_proto_offer_offer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_offer_offer_proto_goTypes = []any{
	(*Offer)(nil),                  // 0: offerService.Offer
	(*GetOfferRequest)(nil),        // 1: offerService.GetOfferRequest
	(*GetOfferResponse)(nil),       // 2: offerService.GetOfferResponse
	(*GetOffersByZhkRequest)(nil),  // 3: offerService.GetOffersByZhkRequest
	(*GetOffersByZhkResponse)(nil), // 4: offerService.GetOffersByZhkResponse
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_proto_offer_offer_proto_depIdxs = []int32{
	5, // 0: offerService.Offer.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: offerService.Offer.updated_at:type_name -> google.protobuf.Timestamp
	5, // 2: offerService.Offer.promotes_until:type_name -> google.protobuf.Timestamp
	0, // 3: offerService.GetOfferResponse.offer:type_name -> offerService.Offer
	0, // 4: offerService.GetOffersByZhkResponse.offers:type_name -> offerService.Offer
	1, // 5: offerService.OfferService.GetOfferById:input_type -> offerService.GetOfferRequest
	3, // 6: offerService.OfferService.GetOffersByZhkId:input_type -> offerService.GetOffersByZhkRequest
	2, // 7: offerService.OfferService.GetOfferById:output_type -> offerService.GetOfferResponse
	4, // 8: offerService.OfferService.GetOffersByZhkId:output_type -> offerService.GetOffersByZhkResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_offer_offer_proto_init() }
func file_proto_offer_offer_proto_init() {
	if File_proto_offer_offer_proto != nil {
		return
	}
	file_proto_offer_offer_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_offer_offer_proto_rawDesc), len(file_proto_offer_offer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_offer_offer_proto_goTypes,
		DependencyIndexes: file_proto_offer_offer_proto_depIdxs,
		MessageInfos:      file_proto_offer_offer_proto_msgTypes,
	}.Build()
	File_proto_offer_offer_proto = out.File
	file_proto_offer_offer_proto_goTypes = nil
	file_proto_offer_offer_proto_depIdxs = nil
}
