package offers

// GetMockOffers Мок-данные объявлений
func GetMockOffers() []Offer {
	return []Offer{
		{
			ID:           1,
			Seller:       "Иван Петров",
			PropertyType: "квартира",
			OfferType:    "продажа",
			PurchaseType: "вторичка",
			RentType:     "",
			Address:      "ул. Ленина, д.10",
			MetroLine:    "Сокольническая",
			MetroStation: "Охотный ряд",
			Floor:        3,
			TotalFloors:  10,
			Area:         60.5,
			Rooms:        2,
			Price:        10000000,
			Photos:       []string{"https://images.cdn-cian.ru/images/kvartira-moskva-shmitovskiy-proezd-2239195740-1.jpg"},
			Description:  "Просторная квартира в центре города.",
		},
		{
			ID:           2,
			Seller:       "Анна Сидорова",
			PropertyType: "апартаменты",
			OfferType:    "аренда",
			PurchaseType: "",
			RentType:     "долгосрок",
			Address:      "пр. Мира, д.5",
			MetroLine:    "Калужско-Рижская",
			MetroStation: "Проспект Мира",
			Floor:        7,
			TotalFloors:  15,
			Area:         40.0,
			Rooms:        1,
			Price:        50000,
			Photos:       []string{"https://images.cdn-cian.ru/images/kvartira-moskva-1y-krasnogvardeyskiy-proezd-2414970105-1.jpg"},
			Description:  "Современные апартаменты рядом с метро.",
		},
		{
			ID:           3,
			Seller:       "ООО \"СтройГрад\"",
			PropertyType: "дом",
			OfferType:    "продажа",
			PurchaseType: "новостройка",
			RentType:     "",
			Address:      "дер. Лесная, д.3",
			MetroLine:    "Нет",
			MetroStation: "Нет",
			Floor:        1,
			TotalFloors:  2,
			Area:         150.0,
			Rooms:        4,
			Price:        25000000,
			Photos:       []string{"https://images.cdn-cian.ru/images/2372914174-1.jpg"},
			Description:  "Современный коттедж с террасой.",
		},
		{
			ID:           4,
			Seller:       "Алексей Смирнов",
			PropertyType: "квартира",
			OfferType:    "аренда",
			PurchaseType: "",
			RentType:     "посуточно",
			Address:      "ул. Тверская, д.1",
			MetroLine:    "Замоскворецкая",
			MetroStation: "Тверская",
			Floor:        5,
			TotalFloors:  12,
			Area:         38.0,
			Rooms:        1,
			Price:        4000,
			Photos:       []string{"https://images.cdn-cian.ru/images/kvartira-moskva-hodynskiy-bulvar-2295375432-1.jpg"},
			Description:  "Квартира для аренды посуточно в центре.",
		},
		{
			ID:           5,
			Seller:       "Антон Иванов",
			PropertyType: "квартира",
			OfferType:    "продажа",
			PurchaseType: "вторичка",
			RentType:     "",
			Address:      "ул. Рождественская, д.8",
			MetroLine:    "Арбатско-Покровская",
			MetroStation: "Бауманская",
			Floor:        9,
			TotalFloors:  14,
			Area:         80.0,
			Rooms:        3,
			Price:        15000000,
			Photos:       []string{"https://images.cdn-cian.ru/images/kvartira-moskva-1y-krasnogvardeyskiy-proezd-2409333786-1.jpg"},
			Description:  "Отличная квартира с видом на реку.",
		},
		{
			ID:           6,
			Seller:       "ООО \"КомфортЖильё\"",
			PropertyType: "апартаменты",
			OfferType:    "продажа",
			PurchaseType: "новостройка",
			RentType:     "",
			Address:      "ул. Набережная, д.15",
			MetroLine:    "Кольцевая",
			MetroStation: "Проспект Мира",
			Floor:        10,
			TotalFloors:  20,
			Area:         90.0,
			Rooms:        3,
			Price:        18000000,
			Photos:       []string{"https://images.cdn-cian.ru/images/kvartira-moskva-1y-krasnogvardeyskiy-proezd-2391976232-1.jpg"},
			Description:  "Элитные апартаменты с панорамными окнами.",
		},
		{
			ID:           7,
			Seller:       "Екатерина Орлова",
			PropertyType: "дом",
			OfferType:    "аренда",
			PurchaseType: "",
			RentType:     "долгосрок",
			Address:      "дер. Лесная, д.7",
			MetroLine:    "Нет",
			MetroStation: "Нет",
			Floor:        1,
			TotalFloors:  1,
			Area:         120.0,
			Rooms:        5,
			Price:        150000,
			Photos:       []string{"https://images.cdn-cian.ru/images/2321137935-1.jpg"},
			Description:  "Уютный дом для семьи с детьми.",
		},
		{
			ID:           8,
			Seller:       "Агентство \"ГородЖильё\"",
			PropertyType: "квартира",
			OfferType:    "аренда",
			PurchaseType: "",
			RentType:     "посуточно",
			Address:      "ул. Новая, д.3",
			MetroLine:    "Люблинско-Дмитровская",
			MetroStation: "Трубная",
			Floor:        6,
			TotalFloors:  9,
			Area:         42.0,
			Rooms:        1,
			Price:        3500,
			Photos:       []string{"https://images.cdn-cian.ru/images/kvartira-moskva-1y-krasnogvardeyskiy-proezd-2409346020-1.jpg"},
			Description:  "Современная квартира на сутки.",
		},
	}
}
