global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'auth'
    static_configs:
      - targets: ['auth:8001']

  - job_name: 'offer'
    static_configs:
      - targets: ['offer:8001']

  - job_name: 'zhk'
    static_configs:
      - targets: ['zhk:8001']

  - job_name: 'ai'
    static_configs:
      - targets: ['ai:8001']