// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: payment.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferId       int32                  `protobuf:"varint,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetOfferId() int32 {
	if x != nil {
		return x.OfferId
	}
	return 0
}

func (x *CreatePaymentRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type CheckTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTypeRequest) Reset() {
	*x = CheckTypeRequest{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTypeRequest) ProtoMessage() {}

func (x *CheckTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTypeRequest.ProtoReflect.Descriptor instead.
func (*CheckTypeRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CheckTypeRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferId       int32                  `protobuf:"varint,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentResponse) GetOfferId() int32 {
	if x != nil {
		return x.OfferId
	}
	return 0
}

func (x *CreatePaymentResponse) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type CheckTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTypeResponse) Reset() {
	*x = CheckTypeResponse{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTypeResponse) ProtoMessage() {}

func (x *CheckTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTypeResponse.ProtoReflect.Descriptor instead.
func (*CheckTypeResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CheckTypeResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type CheckPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     int32                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPaymentRequest) Reset() {
	*x = CheckPaymentRequest{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPaymentRequest) ProtoMessage() {}

func (x *CheckPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPaymentRequest.ProtoReflect.Descriptor instead.
func (*CheckPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *CheckPaymentRequest) GetPaymentId() int32 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

type CheckPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferId       int32                  `protobuf:"varint,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsPaid        bool                   `protobuf:"varint,3,opt,name=is_paid,json=isPaid,proto3" json:"is_paid,omitempty"`
	Days          int32                  `protobuf:"varint,4,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPaymentResponse) Reset() {
	*x = CheckPaymentResponse{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPaymentResponse) ProtoMessage() {}

func (x *CheckPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPaymentResponse.ProtoReflect.Descriptor instead.
func (*CheckPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *CheckPaymentResponse) GetOfferId() int32 {
	if x != nil {
		return x.OfferId
	}
	return 0
}

func (x *CheckPaymentResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CheckPaymentResponse) GetIsPaid() bool {
	if x != nil {
		return x.IsPaid
	}
	return false
}

func (x *CheckPaymentResponse) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type ValidatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     int32                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OfferId       int32                  `protobuf:"varint,2,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePaymentRequest) Reset() {
	*x = ValidatePaymentRequest{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePaymentRequest) ProtoMessage() {}

func (x *ValidatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePaymentRequest.ProtoReflect.Descriptor instead.
func (*ValidatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ValidatePaymentRequest) GetPaymentId() int32 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *ValidatePaymentRequest) GetOfferId() int32 {
	if x != nil {
		return x.OfferId
	}
	return 0
}

type ValidatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePaymentResponse) Reset() {
	*x = ValidatePaymentResponse{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePaymentResponse) ProtoMessage() {}

func (x *ValidatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePaymentResponse.ProtoReflect.Descriptor instead.
func (*ValidatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *ValidatePaymentResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\x0epaymentService\"E\n" +
	"\x14CreatePaymentRequest\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\x05R\aofferId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\"&\n" +
	"\x10CheckTypeRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\"U\n" +
	"\x15CreatePaymentResponse\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\x05R\aofferId\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\".\n" +
	"\x11CheckTypeResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\"4\n" +
	"\x13CheckPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x05R\tpaymentId\"{\n" +
	"\x14CheckPaymentResponse\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\x05R\aofferId\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\x12\x17\n" +
	"\ais_paid\x18\x03 \x01(\bR\x06isPaid\x12\x12\n" +
	"\x04days\x18\x04 \x01(\x05R\x04days\"R\n" +
	"\x16ValidatePaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x05R\tpaymentId\x12\x19\n" +
	"\boffer_id\x18\x02 \x01(\x05R\aofferId\"4\n" +
	"\x17ValidatePaymentResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid2\xff\x02\n" +
	"\x0ePaymentService\x12\\\n" +
	"\rCreatePayment\x12$.paymentService.CreatePaymentRequest\x1a%.paymentService.CreatePaymentResponse\x12P\n" +
	"\tCheckType\x12 .paymentService.CheckTypeRequest\x1a!.paymentService.CheckTypeResponse\x12Y\n" +
	"\fCheckPayment\x12#.paymentService.CheckPaymentRequest\x1a$.paymentService.CheckPaymentResponse\x12b\n" +
	"\x0fValidatePayment\x12&.paymentService.ValidatePaymentRequest\x1a'.paymentService.ValidatePaymentResponseB\x0eZ\f./;paymentpbb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_payment_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),    // 0: paymentService.CreatePaymentRequest
	(*CheckTypeRequest)(nil),        // 1: paymentService.CheckTypeRequest
	(*CreatePaymentResponse)(nil),   // 2: paymentService.CreatePaymentResponse
	(*CheckTypeResponse)(nil),       // 3: paymentService.CheckTypeResponse
	(*CheckPaymentRequest)(nil),     // 4: paymentService.CheckPaymentRequest
	(*CheckPaymentResponse)(nil),    // 5: paymentService.CheckPaymentResponse
	(*ValidatePaymentRequest)(nil),  // 6: paymentService.ValidatePaymentRequest
	(*ValidatePaymentResponse)(nil), // 7: paymentService.ValidatePaymentResponse
}
var file_payment_proto_depIdxs = []int32{
	0, // 0: paymentService.PaymentService.CreatePayment:input_type -> paymentService.CreatePaymentRequest
	1, // 1: paymentService.PaymentService.CheckType:input_type -> paymentService.CheckTypeRequest
	4, // 2: paymentService.PaymentService.CheckPayment:input_type -> paymentService.CheckPaymentRequest
	6, // 3: paymentService.PaymentService.ValidatePayment:input_type -> paymentService.ValidatePaymentRequest
	2, // 4: paymentService.PaymentService.CreatePayment:output_type -> paymentService.CreatePaymentResponse
	3, // 5: paymentService.PaymentService.CheckType:output_type -> paymentService.CheckTypeResponse
	5, // 6: paymentService.PaymentService.CheckPayment:output_type -> paymentService.CheckPaymentResponse
	7, // 7: paymentService.PaymentService.ValidatePayment:output_type -> paymentService.ValidatePaymentResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
