name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Build, Lint, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Set up GOPATH bin
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Download Go dependencies
        run: go mod download

      - name: Install tools
        run: |
          go install github.com/mailru/easyjson/...@latest
          go install github.com/golang/mock/mockgen@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Generate mocks and easyjson
        run: go generate ./...

      - name: Run linter
        run: golangci-lint run --timeout=5m ./...

      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          go test ./... -coverprofile=coverage.out
          echo "\nAverage coverage:"
          go tool cover -func=coverage.out \
            | grep -v 'mock_' \
            | grep -v '_easyjson' \
            | grep -v 'proto' \
            | grep -v 'metrics' \
            | grep -v 'main' \
            | grep -v '^total:' \
            | awk '{ s+=$3; n++ } END { if (n > 0) printf("%.1f%%\n", s/n) }'
  cd:
    name: Deploy to Server
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Set up GOPATH bin
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Download Go dependencies
        run: go mod download

      - name: Install tools
        run: |
          go install github.com/mailru/easyjson/...@latest
          go install github.com/golang/mock/mockgen@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Generate mocks and easyjson
        run: go generate ./...

      - name: Run linter
        run: golangci-lint run --timeout=5m ./...

      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          go test ./... -coverprofile=coverage.out
          echo "\nAverage coverage:"
          go tool cover -func=coverage.out \
            | grep -v 'mock_' \
            | grep -v '_easyjson' \
            | grep -v 'proto' \
            | grep -v 'metrics' \
            | grep -v 'main' \
            | grep -v '^total:' \
            | awk '{ s+=$3; n++ } END { if (n > 0) printf("%.1f%%\n", s/n) }'

      - name: Prepare deployment folder on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_KEY }}
          script: |
            sudo rm -rf /home/backend/2025_1_404
            mkdir -p /home/backend/2025_1_404
            sudo chown $USER:$USER /home/backend/2025_1_404

      - name: Upload project to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_KEY }}
          source: "."
          target: "/home/backend/2025_1_404"

      - name: Restart backend service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_KEY }}
          script: |
            cd /home/backend/2025_1_404
            sudo systemctl restart backend.service
